tv_character_facts = [
  ["What is the name of the coffee shop frequented by the characters in 'Friends'?", "Central Perk"],
  ["Who is the main antagonist in 'Breaking Bad'?", "Gustavo 'Gus' Fring"],
  ["What is the occupation of Ted Mosby in 'How I Met Your Mother'?", "Architect"],
  ["In 'Game of Thrones,' who is known as the 'Mother of Dragons'?", "Daenerys Targaryen"],
  ["Which TV show features a character named Michael Scott?", "The Office"],
  ["In 'Stranger Things,' what is the name of the parallel dimension?", "The Upside Down"],
  ["Who is the bartender in 'Cheers'?", "Sam Malone"],
  ["What is the name of the fictional town where 'Parks and Recreation' is set?", "Pawnee, Indiana"],
  ["Who plays the character of Sheldon Cooper in 'The Big Bang Theory'?", "Jim Parsons"],
  ["In 'The Simpsons,' what is the name of Bart's teacher?", "Edna Krabappel"],
  ["Who is the main character in the TV series 'Sherlock'?", "Sherlock Holmes"],
  ["Which character in 'Friends' is a paleontologist?", "Ross Geller"],
  ["What is the name of the spaceship in 'Firefly'?", "Serenity"],
  ["In 'The Mandalorian,' what is the real name of the character commonly referred to as 'Baby Yoda'?", "Grogu"],
  ["Who is the main character of 'Mad Men'?", "Don Draper"],
  ["In 'Buffy the Vampire Slayer,' what is Buffy's full name?", "Buffy Anne Summers"],
  ["What is the name of the fictional paper company in 'The Office'?", "Dunder Mifflin"],
  ["Who is the central character in 'The Sopranos'?", "Tony Soprano"],
  ["In 'Lost,' what is the name of the island's mysterious inhabitants?", "The Others"],
  ["What is the name of the bar where Ted, Marshall, and Barney hang out in 'How I Met Your Mother'?", "MacLaren's Pub"],
  ["Who is the main antagonist in the TV series 'Dexter'?", "The Ice Truck Killer"],
  ["In 'Friends,' who gets stuck in a pair of leather pants?", "Ross Geller"],
  ["What is the name of the character who runs the diner in 'Gilmore Girls'?", "Luke Danes"],
  ["In 'The Big Bang Theory,' who does Howard Wolowitz marry?", "Bernadette Rostenkowski"],
  ["Who is known as the 'King in the North' in 'Game of Thrones'?", "Jon Snow"],
  ["Which character in 'Seinfeld' is known for saying 'No soup for you!'?", "The Soup Nazi"],
  ["In 'The Walking Dead,' who wields a baseball bat wrapped in barbed wire?", "Negan"],
  ["Who plays the role of Carrie Bradshaw in 'Sex and the City'?", "Sarah Jessica Parker"],
  ["What is the name of the spaceship captain in 'Star Trek: The Next Generation'?", "Jean-Luc Picard"],
  ["In 'The X-Files,' who are the two main FBI agents?", "Fox Mulder and Dana Scully"],
  ["Which character in 'The Office' has a beet farm?", "Dwight Schrute"],
  ["What is the name of the high school in 'Glee'?", "William McKinley High School"],
  ["In 'House,' what is Dr. Gregory House's specialty?", "Diagnostic Medicine"],
  ["Who is the main character in 'The Fresh Prince of Bel-Air'?", "Will Smith"],
  ["What is the name of the hospital in 'Grey's Anatomy'?", "Seattle Grace Hospital"],
  ["Who is the main antagonist in 'Narcos'?", "Pablo Escobar"],
  ["In 'Friends,' who was Monica's first kiss?", "Ross Geller"],
  ["Who plays the character of Eleven in 'Stranger Things'?", "Millie Bobby Brown"],
  ["What is the name of the main character in 'Breaking Bad'?", "Walter White"],
  ["In 'Doctor Who,' what is the name of the Doctor's time machine?", "TARDIS"],
  ["Who is the father of Rachel's baby in 'Friends'?", "Ross Geller"],
  ["What is the name of the fictional town in 'Twin Peaks'?", "Twin Peaks"],
  ["Who plays the role of Sheldon Cooper's girlfriend, Amy, in 'The Big Bang Theory'?", "Mayim Bialik"],
  ["In 'How I Met Your Mother,' what is the name of Barney Stinson's playbook?", "The Playbook"],
  ["Which character in 'The Simpsons' owns the Kwik-E-Mart?", "Apu Nahasapeemapetilon"],
  ["In 'Friends,' who is Chandler Bing's wife?", "Monica Geller"],
  ["What is the name of the family dog in 'Family Guy'?", "Brian Griffin"],
  ["Who plays the role of Dr. Gregory House?", "Hugh Laurie"],
  ["What is the name of the fictional advertising agency in 'Mad Men'?", "Sterling Cooper"],
  ["Who is the main character in the TV series 'Arrow'?", "Oliver Queen"],
  ["In 'The Office,' who is the receptionist?", "Pam Beesly"],
  ["What is the name of the hospital in 'Scrubs'?", "Sacred Heart Hospital"],
  ["Who is the main character in 'Supernatural'?", "Dean Winchester"],
  ["In 'Friends,' what is Joey Tribbiani's famous catchphrase?", "How you doin'?"],
  ["What is the name of the spaceship in 'Star Trek: Deep Space Nine'?", "Deep Space Nine"],
  ["Who is the main character in 'The Wire'?", "Jimmy McNulty"],
  ["In 'Seinfeld,' what is Kramer's first name?", "Cosmo"],
  ["What is the name of the protagonist in 'The Sopranos'?", "Tony Soprano"],
  ["Who plays the role of Meredith Grey in 'Grey's Anatomy'?", "Ellen Pompeo"],
  ["What is the name of the fictional law firm in 'Suits'?", "Pearson Specter Litt"],
  ["Who is the leader of the Sons of Anarchy motorcycle club?", "Jax Teller"],
  ["In 'Buffy the Vampire Slayer,' who is Buffy's first Watcher?", "Rupert Giles"],
  ["What is the name of the high school in 'Veronica Mars'?", "Neptune High School"],
  ["Who plays the character of Liz Lemon in '30 Rock'?", "Tina Fey"],
  ["What is the name of the fictional country in 'The West Wing'?", "The United States (focus is on the White House)"],
  ["Who is the main character in 'Hannibal'?", "Dr. Hannibal Lecter"],
  ["What is the name of the town in 'Pretty Little Liars'?", "Rosewood"],
  ["In 'The Office,' who is the branch manager?", "Michael Scott"],
  ["What is the name of the detective in 'True Detective' season 1?", "Rust Cohle"],
  ["Who plays the role of Rachel Green in 'Friends'?", "Jennifer Aniston"],
  ["What is the name of the spaceship in 'Battlestar Galactica'?", "Battlestar Galactica"],
  ["In 'The Simpsons,' what is Homer's favorite beer?", "Duff Beer"],
  ["Who is the main character in 'The Vampire Diaries'?", "Elena Gilbert"],
  ["What is the name of the hotel in 'American Horror Story: Hotel'?", "Hotel Cortez"],
  ["Who plays the role of Don Draper in 'Mad Men'?", "Jon Hamm"],
  ["In 'Friends,' who is Chandler's roommate before Joey?", "Kip"],
  ["What is the name of the demon-hunting brothers in 'Supernatural'?", "Sam and Dean Winchester"],
  ["Who plays the role of Daenerys Targaryen in 'Game of Thrones'?", "Emilia Clarke"],
  ["What is the name of the prison in 'Prison Break'?", "Fox River State Penitentiary"],
  ["In 'Breaking Bad,' what is Jesse Pinkman's catchphrase?", "Yeah, science!"],
  ["Who is the main character in 'The Handmaid's Tale'?", "June Osborne (Offred)"],
  ["What is the name of the diner in 'Riverdale'?", "Pop's Chock'lit Shoppe"],
  ["Who plays the role of Jon Snow in 'Game of Thrones'?", "Kit Harington"],
  ["What is the name of the fictional island in 'Lost'?", "The Island"],
  ["Who is the main character in 'The Blacklist'?", "Raymond 'Red' Reddington"],
  ["What is the name of the bar in 'It's Always Sunny in Philadelphia'?", "Paddy's Pub"],
  ["Who plays the role of Tony Stark/Iron Man in 'The Marvelous Mrs. Maisel'?",
   "Robert Downey Jr. (Note: Incorrect, Tony Stark is not in 'The Marvelous Mrs. Maisel')",],
  ["What is the name of the fictional newspaper in 'The Newsroom'?", "Atlantis Cable News (ACN)"],
  ["Who is the main character in 'The Walking Dead'?", "Rick Grimes"],
  ["What is the name of the family in 'Arrested Development'?", "The Bluth Family"],
  ["In 'Friends,' who plays the character of Phoebe Buffay?", "Lisa Kudrow"],
  ["What is the name of the fictional city in 'Arrow'?", "Star City"],
  ["Who plays the role of Dexter Morgan in 'Dexter'?", "Michael C. Hall"],
  ["In 'Friends,' who is Ross Geller's second wife?", "Emily Waltham"],
  ["What is the name of the spaceship in 'Star Trek: Voyager'?", "USS Voyager"],
  ["Who plays the role of Dr. John Watson in 'Sherlock'?", "Martin Freeman"],
  ["What is the name of the main character in 'Mr. Robot'?", "Elliot Alderson"],
  ["In 'Friends,' what is the name of Ross and Rachel's daughter?", "Emma Geller-Green"],
  ["Who plays the role of Tyrion Lannister in 'Game of Thrones'?", "Peter Dinklage"],
  ["What is the name of the coffee shop in 'Gilmore Girls'?", "Luke's Diner"],
  ["Who plays the role of Veronica Mars?", "Kristen Bell"],
  ["In 'Friends,' what is Chandler's middle name?", "Muriel"],
  ["What is the name of the fictional town in 'Twin Peaks'?", "Twin Peaks"],
  ["Who is the main character in 'The Sopranos'?", "Tony Soprano"],
  ["What is the name of the school in 'Buffy the Vampire Slayer'?", "Sunnydale High School"],
  ["Who plays the role of Olivia Pope in 'Scandal'?", "Kerry Washington"],
  ["What is the name of the fictional city in 'Gotham'?", "Gotham City"],
  ["Who is the main character in 'The Flash'?", "Barry Allen"],
  ["In 'Friends,' who plays the character of Joey Tribbiani?", "Matt LeBlanc"],
  ["What is the name of the fictional country in 'The Crown'?", "United Kingdom"],
  ["Who plays the role of Sookie Stackhouse in 'True Blood'?", "Anna Paquin"],
  ["What is the name of the coffee shop in 'Friends'?", "Central Perk"],
  ["Who is the main character in 'House of Cards'?", "Frank Underwood"],
  ["In 'Friends,' who is Ross Geller's first wife?", "Carol Willick"],
  ["What is the name of the fictional town in 'Riverdale'?", "Riverdale"],
  ["Who plays the role of Sam Winchester in 'Supernatural'?", "Jared Padalecki"],
  ["In 'Friends,' who plays the character of Monica Geller?", "Courteney Cox"],
  ["What is the name of the fictional city in 'The Wire'?", "Baltimore"],
  ["Who plays the role of Arya Stark in 'Game of Thrones'?", "Maisie Williams"],
  ["What is the name of the spaceship in 'Futurama'?", "Planet Express Ship"],
  ["Who is the main character in 'Westworld'?", "Dolores Abernathy"],
  ["What is the name of the fictional town in 'Stranger Things'?", "Hawkins"],
  ["Who plays the role of Tony Stark/Iron Man in 'The Marvelous Mrs. Maisel'?",
   "Robert Downey Jr. (Note: Incorrect, Tony Stark is not in 'The Marvelous Mrs. Maisel')",],
  ["What is the name of the fictional newspaper in 'The Newsroom'?", "Atlantis Cable News (ACN)"],
  ["Who is the main character in 'The Walking Dead'?", "Rick Grimes"],
  ["What is the name of the family in 'Arrested Development'?", "The Bluth Family"],
  ["In 'Friends,' who plays the character of Phoebe Buffay?", "Lisa Kudrow"],
  ["What is the name of the fictional city in 'Arrow'?", "Star City"],
  ["Who plays the role of Dexter Morgan in 'Dexter'?", "Michael C. Hall"],
  ["In 'Friends,' who is Ross Geller's second wife?", "Emily Waltham"],
  ["What is the name of the spaceship in 'Star Trek: Voyager'?", "USS Voyager"],
  ["Who plays the role of Dr. John Watson in 'Sherlock'?", "Martin Freeman"],
  ["What is the name of the main character in 'Mr. Robot'?", "Elliot Alderson"],
  ["In 'Friends,' what is the name of Ross and Rachel's daughter?", "Emma Geller-Green"],
  ["Who plays the role of Tyrion Lannister in 'Game of Thrones'?", "Peter Dinklage"],
  ["What is the name of the coffee shop in 'Gilmore Girls'?", "Luke's Diner"],
  ["Who plays the role of Veronica Mars?", "Kristen Bell"],
  ["In 'Friends,' what is Chandler's middle name?", "Muriel"],
  ["What is the name of the fictional town in 'Twin Peaks'?", "Twin Peaks"],
  ["Who is the main character in 'The Sopranos'?", "Tony Soprano"],
  ["What is the name of the school in 'Buffy the Vampire Slayer'?", "Sunnydale High School"],
  ["Who plays the role of Olivia Pope in 'Scandal'?", "Kerry Washington"],
  ["What is the name of the fictional city in 'Gotham'?", "Gotham City"],
  ["Who is the main character in 'The Flash'?", "Barry Allen"],
  ["In 'Friends,' who plays the character of Joey Tribbiani?", "Matt LeBlanc"],
  ["What is the name of the fictional country in 'The Crown'?", "United Kingdom"],
  ["Who plays the role of Sookie Stackhouse in 'True Blood'?", "Anna Paquin"],
  ["What is the name of the coffee shop in 'Friends'?", "Central Perk"],
  ["Who is the main character in 'House of Cards'?", "Frank Underwood"],
  ["In 'Friends,' who is Ross Geller's first wife?", "Carol Willick"],
  ["What is the name of the fictional town in 'Riverdale'?", "Riverdale"],
  ["Who plays the role of Sam Winchester in 'Supernatural'?", "Jared Padalecki"],
  ["In 'Friends,' who plays the character of Monica Geller?", "Courteney Cox"],
  ["What is the name of the fictional city in 'The Wire'?", "Baltimore"],
  ["Who plays the role of Arya Stark in 'Game of Thrones'?", "Maisie Williams"],
  ["What is the name of the spaceship in 'Futurama'?", "Planet Express Ship"],
  ["Who is the main character in 'Westworld'?", "Dolores Abernathy"],
  ["What is the name of the fictional town in 'Stranger Things'?", "Hawkins"],
]

tv_character_facts.each do |question, answer|
  Article.create!(question: question, answer: answer).generate_embedding!
end
